config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :workfiles do
    resources :timestamps
  end

  root "workfiles#index"


  resources :orders do
    collection do
      get 'get_order_description'
    end
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/timestamp.rb
class Timestamp < ApplicationRecord
  belongs_to :user
  belongs_to :workfile
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :workfiles
  has_many :timestamps
end

app/models/workfile.rb
class Workfile < ApplicationRecord
  belongs_to :user
  has_many :timestamps
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def show
  end

  def get_order_description
    if Order.exists?(ordernumber: params[:ordernumber])
      @order_description = Order.find_by_ordernumber(params[:ordernumber])
      #@order_description = Order.select(:description).find_by ordernumber: params[:ordernumber]
    end
    if request.xhr?
      respond_to do |format|
        format.json { render :json => @order_description }
      end
    end
  end

  private

    def find_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:ordernumber, :description)
    end
    
  end

app/controllers/timestamps_controller.rb
class TimestampsController < ApplicationController
  before_action :find_timestamp, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def create
    @workfile = Workfile.find(params[:workfile_id])
    @timestamp = @workfile.timestamps.create(params[:timestamp].permit(:description, :ordernumber, :begin_date, :begin_time))
    @timestamp.user_id = current_user.id if current_user
    @timestamp.save

    if @timestamp.save
      redirect_to workfile_path(@workfile)
    else
      render 'new'
    end
  end

  def edit
  end

  def update

    if @timestamp.update(params[:timestamp].permit(:description, :ordernumber, :begin_date, :begin_time))
      redirect_to workfile_path(@workfile)
    else
      render 'edit'
    end
  end

  def destroy
    @timestamp.destroy
    redirect_to workfile_path(@workfile)
  end

private

  def find_timestamp
    @workfile = Workfile.find(params[:workfile_id])
    @timestamp = @workfile.timestamps.find(params[:id])
  end
end

app/controllers/workfiles_controller.rb
class WorkfilesController < ApplicationController
  before_action :find_workfile, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @workfile = if params[:term]
      Workfile.where('title LIKE ?', "%#{params[:term]}%").order('id DESC')
    else
      Workfile.all.order("date DESC")
    end
  end

  def show
  end

  def new
    @workfile = current_user.workfiles.build
  end

  def create
    @workfile = current_user.workfiles.build(workfile_params)

    if @workfile.save
      redirect_to @workfile, notice: "Successfully created new Workfile"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @workfile.update(workfile_params)
      redirect_to @workfile
    else
      render 'edit'
    end
  end

  def destroy
    @workfile.destroy
    redirect_to root_path, notice: "Successfully deleted Workfile"
  end

  private

  def find_workfile
    @workfile = Workfile.find(params[:id])
  end

  def workfile_params
    params.require(:workfile).permit(:title, :description, :date, :term)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/timestamps_helper.rb
module TimestampsHelper
end

app/helpers/workfiles_helper.rb
module WorkfilesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Worktime App
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body
    %nav.navbar.navbar-default
      .container
        .navbar-brand= link_to "Worktime App", root_path

        - if user_signed_in?
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "New Workfile", new_workfile_path
            %li= link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          %ul.nav.navbar-nav.navbar-right
            %li= link_to "Sign Up", new_user_registration_path
            %li= link_to "Sign In", new_user_session_path
    .container
      -flash.each do |name, msg|
        = content_tag :div, msg, class: "alert"

      = yield

app/views/order/_form.html.haml
#company-modal.modal
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
          %span.sr-only Close
        %h4.modal-title= title
        .modal-body
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/order/index.html.haml
h1 H

app/views/order/index.js.erb
$('<%= j render "form", title: "Auftagssuche" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/timestamps/_form.haml
= simple_form_for([@workfile, @workfile.timestamps.build], wrapper: :inline_form) do |f|
  .form-group
    = f.input :ordernumber, :label => false, wrapper: :vertical_input_group2 do
      = f.input_field :ordernumber, as: :string, :label => false, :placeholder => 'ordernumber', class: "form-control order_search"
      %span.input-group-btn
        = link_to orders_path, remote: true, class: "btn btn-default" do
          %span.glyphicon.glyphicon-plus
    = f.input :description, :label => false, wrapper: :field4, :placeholder => 'description', class: "order_description"
    = f.input :begin_date, as: :date_picker, :label => false, :placeholder => 'Date', wrapper: :field2
    = f.input :begin_time, as: :time_picker, :label => false, :placeholder => 'Time', wrapper: :field2
    = f.button :submit, class: 'btn btn-default'

app/views/timestamps/_timestamp.html.haml
%tr{:id => timestamp.id}
  %td= timestamp.ordernumber
  %td= timestamp.description
  %td= timestamp.begin_date
  %td= timestamp.begin_time
  %td
    = link_to 'Edit', edit_workfile_timestamp_path(timestamp.workfile, timestamp), class: "btn btn-primary"
    = link_to 'Delete', [timestamp.workfile, timestamp], method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary"

app/views/timestamps/edit.html.haml
%h1.test Edit Timestamp

= render 'form'

app/views/workfiles/_form.html.haml
= simple_form_for @workfile, html: { multipart: true} do |f|
  -if @workfile.errors.any?
    %errors
      %p
        = @workfile.errors.count
        Preveted this workfile from saving
      %ul
        - @workfile.errors.full.messages.each do |msg|
          %li= msg
  .panel-body
    = f.input :title, input_html: { class: 'form-control' }
    = f.input :date, as: :date_picker
    = f.input :description, input_html: { class: 'form-control' }

  = f.button :submit

app/views/workfiles/_workfile_form.html.erb
<%= simple_form_for @workfile, remote: true do |f| %>
  <% if @workfile.errors.any? %>
    <errors>
      <p>
        <%= @workfile.errors.count %>
        Preveted this workfile from saving
      </p>
      <ul>
        <% @workfile.errors.full.messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </errors>
  <% end %>
  <div class="panel-body">
    <%= f.input :title, input_html: { class: 'form-control' } %>
    <%= f.input :date, :as => :date_picker %>
    <%= f.input :description, input_html: { class: 'form-control' } %>
    <div class="row">
      <div class="col-md-12">
        <%= link_to 'Back', root_path, class: "btn btn-default" %>
        <%= f.button :submit, class: "btn btn-primary" %>
      </div>
    </div>
  </div>

<% end %>

app/views/workfiles/_workfile_row.html.haml
%tr
  %td= link_to @workfile.title, workfile
  %td= workfile.date
  %td= workfile.description
  %td
    = link_to t('edit'), edit_workfile_path(workfile), remote: true, class: "btn btn-default btn-xs"
    = link_to t('delete'), workfile_path(workfile), method: :delete, data: { confirm: t('are_you_sure') }, class: "btn btn-default btn-xs"

app/views/workfiles/edit.html.haml
%h1 Edit workfile

= render 'workfile_form'

app/views/workfiles/index.html.haml
= form_tag(workfiles_path, method: :get) do
  .row
    .col-xs-3
      .input-group
        = text_field_tag :term, params[:term], placeholder: "Search...", class: "form-control"
        .input-group-btn
          = button_tag 'Search', name: nil, class: "btn btn-default btn" do
            %span.glyphicon.glyphicon-search

%br/
%table.table
  %thead
    %tr
      %th title
      %th date
      %th description
  %tbody
    - @workfile.each do |workfile|
      %tr
        %td= link_to workfile.title, workfile
        %td= workfile.date
        %td= workfile.description
        %td
          = link_to t('edit'), edit_workfile_path(workfile), class: "btn btn-default btn-xs"
          = link_to t('delete'), workfile_path(workfile), method: :delete, data: { confirm: t('are_you_sure') }, class: "btn btn-default btn-xs"

app/views/workfiles/new.html.haml
%h1 New workfile

= render 'workfile_form'

app/views/workfiles/new.js.erb
$('<%= j render "form", title: "New Workfile" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/workfiles/new2.html.haml
%h1 New workfile

= render 'form'

app/views/workfiles/show.html.haml
#worktime
  %h3= @workfile.title
  %p= localize @workfile.date
  %p= @workfile.description

#timestamps
  %h3 Timestamps
  %table.table
    %thead
      %tr
        %th ordernumber
        %th description
        %th Date
        %th Time
    %tbody
      = render @workfile.timestamps

  %h3 Add a Timestamp
  = render "timestamps/form"

= link_to t('back'), root_path, class: "btn btn-default"
-if user_signed_in?
  = link_to t('edit'), edit_workfile_path, class: "btn btn-default"
  = link_to t('delete'), workfile_path, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-default'